### ISSUE TITLE
CreateProxy() throws TargetInvocationException on Silverlight 4.0

### ISSUE THREAD

**Issue by duncan-bayne** [philiplaureano/LinFu#15]
I am running LinFu.DynamicProxy.dll 1.0.3.18540 on Silverlight 4.0.  The following test:

```
public interface IFoo
{
}

public class DummyClass : IFoo, IInterceptor
{
    public DummyClass()
    {
        var factory = new ProxyFactory();
        factory.CreateProxy<IFoo>(this);
    }

    public object Intercept(InvocationInfo info)
    {
        return null;
    }
}

[TestClass]
public class Tests
{
    [TestMethod]
    public void CreateProxyShouldNotRaiseException()
    {
        Assert.IsNotNull(new DummyClass());
    }
}
```

... causes an exception to be thrown:

```
TargetInvocationException was unhandled

    Exception has been thrown by the target of an invocation.

       at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
       at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache)
       at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache)
       at System.Activator.CreateInstance(Type type, Boolean nonPublic)
       at System.Activator.CreateInstance(Type type)
       at LinFu.DynamicProxy.ProxyFactory.CreateProxy[T](IInterceptor interceptor, Type[] baseInterfaces)
       at LinFuIssue.DummyClass..ctor()
       at LinFuIssue.Tests.CreateProxyShouldNotRaiseException()

This test result also contained an inner exception:

    System.Security.VerificationException: Operation could destabilize the runtime.
       at DummyClassProxy..ctor()
```

The same code compiled & run on .NET 4.0 using the LinFu.DynamicProxy.dll 1.0.3139.17910 works just fine.

**Comment by duncan-bayne** [comment]
Closing this; haven't used Silverlight in a decade :)
